#!/usr/bin/env bash
# Print num from 1 to 100
a=1
while [ $a -lt 101 ]; do
	if [ $((a % 15)) -eq 0 ]; then
        	echo "FizzBuzz"
	elif [ $((a % 3)) -eq 0 ]; then
        	echo "Fizz"
	elif [ $((a % 5)) -eq 0 ]; then
        	echo "Buzz"
	else
        	echo $a
	fi
	a=$((a + 1))
done
