#!/usr/bin/env bash
# Print Best School ten times (Plus Hi)
a=0
while [ $a -lt 10 ]
do
	a=$((a+1))
	if [ $a -eq 4 ]; then
		echo "bad luck"
	elif [ $a -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
