#!/usr/bin/env bash
#File for checking
school="./school"
if [ -e "$school" ]; then
	echo "school file exists"
	if [ -s "$school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$school" ]; then
                echo "school is a regular file"
        fi
fi
