#!/usr/bin/env bash
# Script that does all things more than you imagine
filename="/var/run/myscript.pid"
pid="echo $$"
echo "$pid" > "$filename"
say_my_name() {
        echo "I hate the kill command"
}

trap say_my_name SIGTERM
a=0
while [ $a -lt 1 ]; do
        echo "To infinity and beyond"
        sleep 2
done
