#!/usr/bin/env bash
# Script that takes arguments like start, stop and restart
start_service() {
	touch /var/run/my_process.pid
	pid="echo $$"
	echo "$pid" >> /var/run/my_process.pid
	echo "manage_my_process started"
	./manage_my_process
}
stop_service() {
	pid="echo $$"
	pkill -9 "$pid"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}
restart_service() {
        pid="echo $$"
        pkill -9 "$pid"
        rm /var/run/my_process.pid
	echo "$pid" >> manage_my_process
        echo "manage_my_process restarted"
	./manage_my_process
}
case "$1" in
	start)
		start_service
		;;
	stop)
		stop_service
		;;
	restart)
		restart_service
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
