#!/usr/bin/env bash
# Script that takes arguments like start, stop and restart
file="/var/run/my_process.pid"
start_service() {
	./manage_my_process &
    	pid=$!
    	echo "$pid" > "$file"
	echo "manage_my_process started"
}
stop_service() {
	pid=$!
	kill -9 "$pid"
	rm "$file"
	echo "manage_my_process stopped"
}
restart_service() {
        pid=$!
        kill -9 "$pid"
        rm "$file"
        echo "manage_my_process restarted"
	./manage_my_process &
        pid=$!
        echo "$pid" > "$file"
}
case "$1" in
	start)
		start_service
		;;
	stop)
		stop_service
		;;
	restart)
		restart_service
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
