#!/usr/bin/env bash
# Script that takes arguments like start, stop and restart
start_service() {
	./manage_my_process
	filename="/var/run/myscript.pid"
	pid="echo $$"
	echo "$pid" > "$filename"
	echo "manage_my_process started"
}
stop_service() {
	pid="echo $$"
	pkill -9 $pid
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}
restart_service() {
        pid="echo $$"
        pkill -9 $pid
        rm /var/run/my_process.pid
	./manage_my_process
	filename="/var/run/myscript.pid"
	echo "$pid" > "$filename"
        echo "manage_my_process restarted"
}
case "$1" in
	start)
		start_service
		;;
	stop)
		stop_service
		;;
	restart)
		restart_service
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
