#!/usr/bin/env bash
# Script that displays text indefinitely
say_my_name() {
	echo "I am invincible!!!"
}
trap say_my_name SIGTERM
a=0
while [ $a -lt 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
